server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-9527

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: getway-9527.com
    prefer-ip-address: true


info:
  app.name: cloud_parent
  company.name: www.wxb.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

zuul:
  ignored-services: "*"
  prefix: /at
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
